// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBjdEJzsxZNReA3Wpd5j2O93r95UVXgI',
    appId: '1:459801809691:web:efc9a7ca4671b3ddca39be',
    messagingSenderId: '459801809691',
    projectId: 'login-example-42041',
    authDomain: 'login-example-42041.firebaseapp.com',
    storageBucket: 'login-example-42041.appspot.com',
    measurementId: 'G-K39DNY5NP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAppA_Kxyng6OJq391N0yA2cZN8FPvefVk',
    appId: '1:459801809691:android:e609dd1429dcf180ca39be',
    messagingSenderId: '459801809691',
    projectId: 'login-example-42041',
    storageBucket: 'login-example-42041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD31zVOa2no5YIQVnV2T0UUk4T2fxB-6dQ',
    appId: '1:459801809691:ios:d214362083920829ca39be',
    messagingSenderId: '459801809691',
    projectId: 'login-example-42041',
    storageBucket: 'login-example-42041.appspot.com',
    iosBundleId: 'com.example.loginproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD31zVOa2no5YIQVnV2T0UUk4T2fxB-6dQ',
    appId: '1:459801809691:ios:b9b77385a3036b86ca39be',
    messagingSenderId: '459801809691',
    projectId: 'login-example-42041',
    storageBucket: 'login-example-42041.appspot.com',
    iosBundleId: 'com.example.loginproject.RunnerTests',
  );
}
